"""supress approve/reject registration mails

Revision ID: a9f203180b00
Revises: 869fb2760b41
Create Date: 2025-09-19 08:20:44.800909
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a9f203180b00'
down_revision = '869fb2760b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('update_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.sql.false()), schema='event_registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'update_notifications_enabled', schema='event_registration')
    # ### end Alembic commands ###
